Homework L3-l3-t10/11/12 //packed 3 tasks in one
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #109
Opened 2021-11-20 07:24 UTC by Denteron

lesson 3 -level 2 - task 10,11,12

пытался придумать куда там запихать указанную - this. //но так и не придумал, ибо конфликтов в строках как бы не было.

2021-11-20 07:30 UTC, Denteron commented
Я еще и забыл пакеты поменять..  "Фейспалм" хотел поменять пакеты ибо с бранчем возиться точно не планировал, а пакеты в итоге ушли на 10 такс все, я так понимаю это не проблема, но я попробую быть внимательнее и указывать более детально :) Ибо сейчас такая мета пошла что задачи в пачках стали нормой, а привычки нет :)

2021-11-20 10:15 UTC, daniilsjb requested changes
Насчёт пакетов ладно, главное чтоб решения были. Но касаемо `this` тут есть момент: в задании требуется, чтобы имя робота было его _свойством_, а не _параметром_ метода. Например:

```java
class Robot {
    // Здесь name - это свойство
    String name;
}
```

Свойства - это как переменные, привязанные к объекту (роботу). Их можно задать и прочитать только через робота:

```java
// Здесь мы задаём имя только первому роботу
Robot rob1 = new Robot();
rob1.name = "Ololo";

// Здесь мы задаём имя только второму роботу
Robot rob2 = new Robot();
rob2.name = "Kolja";

// Их имена совершенно независимы, поэтому они остаются разными
System.out.println(rob1.name);
System.out.println(rob2.name);
```

Внутри класса свойства используются через `this`:

```java
class Robot {
    String name;

    // Обратите внимание: этот метод ничего не принимает.
    // Имя робота он берёт уже из самого объекта, на котором вызван.
    public void sayYourName() {
        System.out.println("My name is " + this.name + ".");
    }
}
```

В задании также необходим конструктор, чтобы позволить программе задавать имя роботу сразу при его создании, типа так:

```java
Robot rob1 = new Robot("Ololo");
Robot rob2 = new Robot("Kolja");
```

Как-то так 🙂

2021-11-20 15:21 UTC, Denteron commented
Спасибо за развернутый ответ :)

2021-11-20 15:30 UTC, Denteron commented
Я кстати с оленятил жестко, в последующих заданиях на "найти ошибку" используют такую же механику :)

2021-11-21 10:56 UTC, daniilsjb requested changes
Осталось буквально одно маленькое изменение в конструкторе. Я готов засчитать и как есть, но поскольку это актуально для следующих заданий, то лучше подправить сразу :D

И я вернул ветку к тому комиту с новой версией, так что нужно будет запуллить изменения.

2021-11-21 10:56 UTC, daniilsjb commented on src/main/java/students/deniss_fomins/lesson_3/level_3/task_10/Robot.java
> +    }
Хех, а вот тут как раз параметр был нужен 🧐

Когда вызывается конструктор, робот ещё не создан, и потому у него ещё нет имени. Чтобы указать имя при создании, его нужно передать как параметр конструктору. После этого он своё имя запоминает, и далее его можно спокойно читать через `this`.

Тогда получается такой код (взятo буквально из описания задания):

```java
Robot(String robotName) {
    this.name = robotName;
}
```

И вот теперь мы можем создавать роботов таким образом:

```java
// Передаём имя напрямую в new.
Robot rob1 = new Robot("Ololo");
rob1.sayYourName();
```

2021-11-22 18:25 UTC, daniilsjb approved these changes
👍

2021-11-22 18:25 UTC, merged