Lesson 3, level 2-4 tasks. Level 5 have questions.
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #115
Opened 2021-11-21 11:08 UTC by IDanste

Доброго дня. Задание с собакой не смог побороть, можешь объяснить как правильно писать, начиная с 19 задания?

2021-11-21 11:52 UTC, daniilsjb requested changes
Кроме собаки нужно ещё подправить задание 16.

2021-11-21 11:52 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/lesson_3/level_4/task_16/BankAccount.java
> +    }
Строчка `this.moneyAmount = moneyAmount;` должна быть помещена в _конструктор_ (тот метод, у которого имя совпадает с названием класса), а не в отдельный метод. Метод `moneyAmount` даже не принимает количества денег и в целом никогда не вызывается 🤔

2021-11-21 11:52 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/lesson_3/level_5/Dog.java
> +
С собакой тут уже посложнее, это да 😉

Во-первых, в заданиях говорится, что у собаки есть кличка, возраст и цвет. Это данные, которые описывают каждую собаку, и у каждой собаки они могут быть разные (одна собака может зваться Alex, другая - Bobby, и т.д.)

Следовательно, первый шаг заключается в том, чтобы выделить эти данные как _свойства_ класса. Не переменные внутри методов, а именно свойства:

```java
class Dog {
    private String name;
    private String color; // С цветом а забегаю уже на задания 20 и 21, но суть та же.
    private int age;      // С типами данных пока можно не заморачиваться, int будет достаточно.

    ...
}
```

Здесь важно отметить, что мы пока не задали никаких значений этим свойствам, это будет сделано следующим шагом. Я также сделал их приватными, чтобы наружний код не мог их напрямую читать и изменять.

2021-11-21 11:52 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/lesson_3/level_5/Dog.java
> +
Следующий шаг: "кличку/возраст/цвет указывают во время создания". Во время создания любого объекта вызывается конструктор. В нашем случае конструктор должен получить информацию о собаке и сохранить её в свойства объекта. Довольно просто:

```java
class Dog {
    // Тут свойства из предыдущего коммента

    public Dog(String dogName, String dogColor, int dogAge) {
        this.name = dogName;
        this.color = dogColor;
        this.age = dogAge;
    }
}
```

Теперь при создании собаки мы должны указать её имя, цвет, и возраст. Эти значения могут быть уникальны для каждой собаки, и будут к ней привязаны. Вот так мы можем создавать собак в `DogDemo`:

```java
class DogDemo {
    public static void main(String[] args) {
        Dog dog1 = new Dog("Alex", "Black", 3);
        Dog dog2 = new Dog("Boston", "Ginger", 9);
    }
}
```

2021-11-21 11:52 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/lesson_3/level_5/Dog.java
> +    }
Далее код становится очень простым. Нам нужен метод `voice`, который выведет информацию о собаке. Если делать все задания вместе, то можно сразу объединить все условия в одно:

```java
class Dog {
    // Тут свойства и конструктор

    public void voice() {
        // Выводим кличку три раза
        for (int i = 0; i < 3; i++) {
            System.out.println("Woof! I'm " + this.name + "!");
        }

        // Выводим возраст
        System.out.println("I'm " + this.age + " years old!");

        // С цветом уже по аналогии 🧐
    }
}
```

Через `this` программа способна прочитать (и даже изменить) свойства текущей собаки. Именно это мы и делаем.

2021-11-21 11:52 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/lesson_3/level_5/Dog.java
> +    }
Здесь всё ещё проще, нужно просто увеличивать свойство `age` этой собаки на единицу:

```java
class Dog {
    ...

    public void happyBirthday() {
        this.age += 1;
        System.out.println("Happy birthday to me, I'm now " + this.age + " years old!");
    }
}
```

2021-11-21 11:52 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/lesson_3/level_5/Dog.java
> +    }
Остальные методы уже по аналогии: `changeColor` должен принять в качестве параметра новый цвет, и далее записать его в свойство `this.color`.

2021-11-21 11:52 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/lesson_3/level_5/DogDemo.java
> +        System.out.println();
Здесь нужно будет продемонстрировать работу с каждым методом. Создать какую-то собаку, подать голос, отпраздновать день рождения, подать голос снова, изменить цвет, подать голос снова. Всё такое.

2021-11-21 17:46 UTC, IDanste commented
Справился с собакой и еще небольшую помарку нашел в 16 задании, не поменял на фамилию. Спасибо за объяснение, практически сразу дошло. ツ

2021-11-21 17:57 UTC, IDanste commented
Вопрос появился, при коммите, случайно удалил класс Robot с первого задания, как можно его восстановить или нужно заново код писать?

2021-11-21 19:53 UTC, IDanste commented
Нашел как восстановить класс, все в порядке.

2021-11-22 18:07 UTC, daniilsjb approved these changes
Теперь с собакой стало лучше, хотя ещё есть на что обратить внимание 😄

2021-11-22 18:07 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/lesson_3/level_5/Dog.java
> +    private String newName;
Строго говоря у собаки нет таких свойств, как новый цвет или новое имя, поскольку это понятия абстракные. Для изменения свойств нужны методы, принимающие новое значения в качестве параметра, типа такого:

```java
void setColor(String newColor) {
    this.color = newColor;
}
```

Но всё же разница между свойствами и параметрами в первый раз может быть сложной для восприятия, так что всё в порядке. В будущих заданиях будет ещё много времени на тренировку с ООП :)

2021-11-22 18:07 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/lesson_3/level_5/Dog.java
> +    }
В методе `sayAgeAndName` менять свойства вообще не нужно, ему достаточно было только вывести информацию о собаке в консоль. **Имя и возраст уже были присвоены при вызове конструктора.**

Про `changeColor` выше написал, тут стоило принимать новый цвет как параметр, чтобы его можно было использовать и для других цветов, кроме серого.

2021-11-22 18:07 UTC, merged