Home work from lesson 3
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #138
Opened 2021-11-22 16:28 UTC by svetlanacibula

Please take a look on my homework: Tasks 1 to 28

2021-11-22 17:53 UTC, daniilsjb requested changes
Маленькая ошибка в 16-ом задании, на внимательность :D В остальном прекрасно!

2021-11-22 17:53 UTC, daniilsjb commented on src/main/java/students/svetlana_cibula/lesson_3/level_4/task_16/BankAccount.java
> +    }
Тут должно быть `return this.ownerLastName;` :)

2021-11-22 17:53 UTC, daniilsjb commented on src/main/java/students/svetlana_cibula/lesson_3/level_5/task_19/Dog.java
> +        age = age + byOneYear;
Можно ещё использовать более краткую запись: `this.age += byOneYear`.

2021-11-23 15:19 UTC, svetlanacibula commented on src/main/java/students/svetlana_cibula/lesson_3/level_5/task_19/Dog.java
> +        age = age + byOneYear;
Поправила

2021-11-23 15:20 UTC, svetlanacibula commented on src/main/java/students/svetlana_cibula/lesson_3/level_4/task_16/BankAccount.java
> +    }
Изменения перезалила.

2021-11-23 15:27 UTC, daniilsjb approved these changes
👍

2021-11-23 15:27 UTC, merged