Lesson 3. Homework
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #174
Opened 2021-11-24 09:43 UTC by ri4ardliepa

2021-11-24 18:33 UTC, daniilsjb requested changes
Есть небольшие неточности в заданиях 16, 27 и 28. В остальном всё круто, многие из этих заданий значительно тяжелее предыдущих! И со структурой файлов всё теперь тоже прекрасно :D

2021-11-24 18:33 UTC, daniilsjb commented on src/main/java/students/richard_liepa/lesson_3/level_4/task_16/BankAccount.java
> +    String getOwnerLastName() {return this.ownerFirstName;}
Тут должно быть `return this.ownerLastName`. Не все ошибки способна подметить IDE 😥

2021-11-24 18:33 UTC, daniilsjb commented on src/main/java/students/richard_liepa/lesson_3/level_7/task_27/Circle.java
> +    }
Строго говоря этот метод должен возвращать площадь, а не выводить в консоль:

```java
double calculateArea() {
    return Math.PI * (radius * radius);
}
```

Вывод должен происходить на стороне `main`:

```java
Circle circle = new Circle(55.0);
System.out.println("The area is: " + circle.calculateArea()).
```

2021-11-24 18:33 UTC, daniilsjb commented on src/main/java/students/richard_liepa/lesson_3/level_7/task_28/Product.java
> +    }
Метод `actualPrice` должен считать цену с учётом скидки. Ему не нужно что-либо изменять в свойствах класса или выводить что-то в консоль. Тут будет что-то типа такого:

```java
double actualPrice() {
    return (1.0 - discount) * regularPrice;
}
```

Также обращу внимание на то, что тут нужна была другая формула 🤫 Не обязательно использовать именно ту, что я указал выше, но нас всё же интересует сама цена, а не скидка.

2021-11-24 18:33 UTC, daniilsjb commented on src/main/java/students/richard_liepa/lesson_3/level_7/task_28/Product.java
> +    }
Тогда тут всё просто:

```java
void info() {
    System.out.println("Price with discount is: " + this.actualPrice());
}
```

2021-11-25 09:10 UTC, ri4ardliepa commented on src/main/java/students/richard_liepa/lesson_3/level_4/task_16/BankAccount.java
> +    String getOwnerLastName() {return this.ownerFirstName;}
Да, что-то я сам не внимательно сделал. Я так понимаю в 17 строке, начиная с return, после того как сделали getOwnerLastname, также и там должно быть ownerLastName

2021-11-25 09:11 UTC, ri4ardliepa commented on src/main/java/students/richard_liepa/lesson_3/level_7/task_28/Product.java
> +    }
Хорошо, я понял, сейчас всё исправлю и отправлю request ещё раз. Спасибо!

2021-11-25 09:12 UTC, ri4ardliepa commented on src/main/java/students/richard_liepa/lesson_3/level_4/task_16/BankAccount.java
> +    String getOwnerLastName() {return this.ownerFirstName;}
Да, благодаря вам понял наконец как структуру адекватно использовать

2021-11-25 09:48 UTC, ri4ardliepa commented on src/main/java/students/richard_liepa/lesson_3/level_4/task_16/BankAccount.java
> +    String getOwnerLastName() {return this.ownerFirstName;}
Я смотрю на 16 задание и я так понял, что эту ошибку вы исправили за меня, да? А то там всё верно как я смотрю

2021-11-25 09:53 UTC, ri4ardliepa commented on src/main/java/students/richard_liepa/lesson_3/level_7/task_27/Circle.java
> +    }
Да, теперь понял, используем sout в классе где находится main. Спасибо!

2021-11-25 10:13 UTC, ri4ardliepa commented on src/main/java/students/richard_liepa/lesson_3/level_7/task_28/Product.java
> +    }
Извинитен, но я не очень понял как должен выглядить код в итоге...Разве в моём коде строки 18 и 19, не считает цену с учётом скидки? То есть regularPrice * discount? Объясните, плиз :(

2021-11-25 10:17 UTC, ri4ardliepa commented
Я внёс изменения во все задания которые вы отметили с ошибками и сделал commit&push. Надеюсь, что у вас видны изменения, а то не могу сделать request :(

2021-11-25 16:13 UTC, daniilsjb approved these changes
Изменения пришли, достаточно делать только commit и push. Отлично! 🚀

2021-11-25 16:13 UTC, merged