Homework l4-l3-t9
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #181
Opened 2021-11-24 12:33 UTC by Denteron

lesson 4 - level 3 -task 9

2021-11-24 18:22 UTC, daniilsjb requested changes

2021-11-24 18:22 UTC, daniilsjb commented on src/main/java/students/deniss_fomins/lesson_4/level_3/task_9/BestOfThree.java
> +        }
Один нюанс: если среди трёх чисел есть равные, то эти проверки не будут проходить. Если заменить все `>` на `>=` то должно работать. По сути мы берём противоположную логику: число можно считать наибольшим, если нет числа больше него 🤓

2021-11-25 04:00 UTC, Denteron commented
В целом мое построение мне понравилось, но вы правы в том что я не усмотрел вариант когда вводится 3 одинаковых числа, и типо он нечего не выводил. Я еще вчера перед отправкой проверил код на корректную работу и он выдавал все верно при 3х разных вариантах ибо неважно что номер 2 и 3 будут равны, ибо номер 1 больше их обоих и он будет победителем. Ну по крайней мере все было именно так. Но то что я действительно не предусмотрел ввод 3х одинаковых чисел это я да что-то погорячился :)

2021-11-25 05:43 UTC, Denteron commented
блин я погнял... если 2 победителя... то что покажет прога :) )пошел переделывать еще раз :)

2021-11-25 07:25 UTC, Denteron commented
Обновил, добавил = для вариантов когда 2 из 3 чисел будут равны и при этом больше 3го.

2021-11-25 16:11 UTC, daniilsjb approved these changes
Думаю, самый полезный урок здесь в том, что даже у простых задач бывают неочевидные edge case-ы :)

2021-11-25 16:11 UTC, merged