St pavels fomins lesson 4 level 4 task 10
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #200
Opened 2021-11-26 20:05 UTC by nextlevelplay

Добрый вечер! Немного "налажал" с коммитом - остался с другого задания, а меня хлебом не корми, лишь бы мышкой пощёлкать =D Через git reset HEAD потереть не получилось, видимо я ещё "юнлинг" и до подована мне ещё далеко =))))

2021-11-26 22:00 UTC, daniilsjb requested changes
Я ничего лишнего не вижу, так что наверное стёрлось правильно, падаван 🤔

У методов `even` и `maxOfTwoNumbers` есть ошибки в реализации. Также стоит упростить сам класс, изменив свойства на параметры (я уже надоел с этими тонкостями, но это важно 🧐).

2021-11-27 10:26 UTC, nextlevelplay commented on src/main/java/students/pavels_fomins/lesson_4/level_4/task_10/Calculator.java
> +    }
Понял, перемудрил ;) Просто думал, что один раз передав в конструктор числа ими уже оперировать во всех методах. Но, затем появилась ещё и третья и цифра и застала меня врасплох. 

Раз уж зашла речь о важности понятий что да где, позвольте уточнить?
Я ведь правильно понимаю?
И внутри метода «в скобках» - можно передавать переменные и/или описывать их заранее в «в свойствах»?
![AE36B057-85DD-4397-B7EB-32EF26A5B2FD](https://user-images.githubusercontent.com/80169865/143677194-1252ec42-b026-4861-b160-3753b19a3267.jpeg)

2021-11-27 10:56 UTC, nextlevelplay commented on src/main/java/students/pavels_fomins/lesson_4/level_4/task_10/Calculator.java
> +    }
![Uploading FA7DFED9-0CE2-48B2-B0DD-B34EBE58D7D2.jpeg…]()

2021-11-27 10:56 UTC, daniilsjb commented on src/main/java/students/pavels_fomins/lesson_4/level_4/task_10/Calculator.java
> +    }
Всё верно! :D

_Метод_ - это блок кода, который можно использовать много раз для решения каких-то задач (типа метод поиска наибольшего числа, или метод сортировки). Все инструкции программы как правило находятся в методах (`main` это тоже метод, но особенный).

_Параметрамы_ - это то, что в круглых скобках после имени метода. Они как переменные, только их значения мы передаём уже при вызове метода (и они каждый раз могут быть разные). Конкретные значения, которые передаются в метод, называются _аргументами_. То есть у метода `sum` есть параметры `firstNumber` и `secondNumber`, а аргументами могут быть, скажем, числа `2` и `3`.

_Свойства_ - это переменные, привязанные к объекту. Все методы объекта имеют доступ к его свойствам. По сути свойства используются для того, чтобы описать объект или хранить какие-то данные которые должны быть общими для всех методов.

2021-11-27 10:57 UTC, nextlevelplay commented on src/main/java/students/pavels_fomins/lesson_4/level_4/task_10/Calculator.java
> +    }
Тогда я слегка запутался ;) Зачем тогда переменные объявлять тут?

2021-11-27 10:58 UTC, nextlevelplay commented on src/main/java/students/pavels_fomins/lesson_4/level_4/task_10/Calculator.java
> +    }
![Uploading 70FE1E89-C9B2-4520-AEB7-9CA9C6A7E85E.jpeg…]()

2021-11-27 12:23 UTC, daniilsjb commented on src/main/java/students/pavels_fomins/lesson_4/level_4/task_10/Calculator.java
> +    }
Картинку не вижу 🤔

Именно в этом задании логика такая: разные математические операции принимают разные параметры, и между ними никакой связи нет. Я могу переиспользовать один и тот же калькулятор, чтобы посчитать сумму чисел `2` и `3`, потом произведение между `12`, `-6`, потом найти максимальное числое между `6`, `-8`, `4`, и затем узнать, чётное ли число `78`. Места для свойств тут просто нет :)

2021-11-27 13:06 UTC, nextlevelplay commented on src/main/java/students/pavels_fomins/lesson_4/level_4/task_10/Calculator.java
> +    }
Жалко, что картинки не видать ;) Напишу тогда ручками:

class Calculator {

     double num1;
     double num2;

     public Calculator(double num1, double num2) {
         this.num1 = num1;
         this.num2 = num2;
     }
     
Это конструктор - верхние num1 и num2 нам тоже не нужны, раз мы передаём их тип и название в скобках конструктора? 😅

2021-11-27 13:14 UTC, daniilsjb commented on src/main/java/students/pavels_fomins/lesson_4/level_4/task_10/Calculator.java
> +    }
А, вроде понимаю вопрос 🧐

Верхние `num1` и `num2` (свойства) отличаются от тех `num1` и `num2`, которые принимает конструктор (параметры). Это различие можно наглядно увидеть за счёт того, что мы ссылаемся на них по-разному: через `this` мы ссылаемся на свойства, а без него на параметры.

Конструктор - это тоже метод, поэтому у него тоже могут быть параметры, которые задаются только при его вызове. Просто под вызовом здесь подразумевается создание объекта. Поэтому в этом коде ничего лишнего нет, но только если целью класса является хранить два числа, заданные при создании объекта. Но поскольку именно этому классу свойства не нужны, то и конструктор, и переменные сверху можно убрать.

2021-11-27 19:05 UTC, nextlevelplay commented
Спасибо за пояснение =) Переделал код, думаю большая ошибка была у меня в том, что я хотел везде оперировать введёнными в калькулятор данными, а не каждый раз их указывать в методах - но наворотил там всякого =) Главную мысль я уловил - надо быть проще)) Викторина - это конечно весело и с творческим подходом, но пока рановато мне "выпендриваться" =DD

2021-11-27 19:57 UTC, daniilsjb approved these changes
Вот, теперь прекрасно! А экспериментировать всё равно полезно, так что это в любом случае ценный опыт :D

2021-11-27 19:57 UTC, merged