Homework l4-l6-t16
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #216
Opened 2021-11-29 05:39 UTC by Denteron

lesson 4 - level 6 -task 16

2021-11-29 05:41 UTC, Denteron commented
Ах да, я понимаю что ценны в целых числах это не шибко корректно, но если нужно заменить на дабл то могу исправить :)

2021-11-29 17:21 UTC, daniilsjb requested changes

2021-11-29 17:21 UTC, daniilsjb commented on src/main/java/students/deniss_fomins/lesson_4/level_6/task_16/Stock.java
> +        if (this.actualPrice < this.minPrice || this.minPrice == 0){
По идее здесь проверка на ноль не нужна. Не важно, какое значение у `minPrice` - если новая цена меньше, значит это новый минимум.

2021-11-29 17:21 UTC, daniilsjb commented on src/main/java/students/deniss_fomins/lesson_4/level_6/task_16/StockTest.java
> +    }
Да, насчёт теста хорошо бы подправить 🤔 Этот класс можно по сути переделать под `StockDemo`, поскольку он просто демонстрирует работу с акциями.

В тестовом коде стоит именно проверять, что вернул метод `getPriceInformation()`, либо напрямую проверять каждое свойство по отдельности. Всё-таки смысл автоматического тестирования в том, чтобы не нужно было сравнивать результаты самостоятельно :)

2021-11-30 16:38 UTC, Denteron commented
Закинул апдейт теста, он все еще по старинке сделанный, ибо оптимизировать тесты я прям хз как. Что касательно проверки на ноль, то реально она там нахрен не уперлась, это я когда пилил код из говна и палок, выстраивал логику и какую чушь я там не прописывал со старта, эта проверка на ноль просто пережиток прошлого трая :)

2021-11-30 17:37 UTC, daniilsjb approved these changes
Понимательно 😄👍

2021-11-30 17:37 UTC, merged