Artjom Glusonok Lesson 4 Level 6 Task 16
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #221
Opened 2021-11-29 18:51 UTC by Glusonok

2021-11-29 18:52 UTC, Glusonok commented
Привет . Не могу понять как мне задействовать новую цену . Подскажи пожалуйста 😇

2021-11-30 17:52 UTC, daniilsjb commented on src/main/java/students/artjom_glusonok/lesson_4/level_6/Stock.java
> +        System.out.println(name + " present value is " + price);
Здесь стоит именно возвращать строку, а не выводить её в консоль. Причина в том, что тогда этот класс легче тестировать - можно просто убедиться, что была возвращена правильная строка. А вывод пишется в `main`.

В любом случае, тут ещё нужно указать `minPrice` и `maxPrice`. В задании дан полный пример вывода в консоль :)

2021-11-30 17:52 UTC, daniilsjb commented on src/main/java/students/artjom_glusonok/lesson_4/level_6/Stock.java
> +    }
Так, здесь логика простая:
- поскольку мы задаём новую цену, то в текущую цену (свойство `price`) нужно записать значение `newPrice`;
- если новая цена больше максимальной, то записываем новую цену в максимальную;
- если новая цена меньше минимальной, то записываем новую цену в минимальную.

Будет выглядеть примерно так:

```java
void updatePrice(int newPrice) {
    this.price = newPrice;
    if (newPrice > this.maxPrice) {
        // ...
    }
    if (newPrice < this.minPrice) {
        // ...
    }
}
```

И ещё, этот метод должен только обновить свойства класса. Выводить что-либо в консоль не нужно!

2021-11-30 17:52 UTC, daniilsjb commented on src/main/java/students/artjom_glusonok/lesson_4/level_6/Stock.java
> +}
В этом задании также нужен тестовый класс. Опять-таки, рекомендую в каждом тестовом сценарии вызывать `getPriceInformation()` и проверять содержимое возвращённой строки.

2021-12-01 19:14 UTC, daniilsjb requested changes
Одна маленькая опечатка 😥

2021-12-01 19:14 UTC, daniilsjb commented on src/main/java/students/artjom_glusonok/lesson_4/level_6/Stock.java
> +        maxima.updatePrice(54);
Если здесь поменять порядок на 2 → 54 → 50, то тест провалится 🤔

2021-12-01 19:14 UTC, daniilsjb commented on src/main/java/students/artjom_glusonok/lesson_4/level_6/Stock.java
> +        }
Причина: здесь должно быть `this.price > this.maxPrice` :)

2021-12-02 18:04 UTC, daniilsjb approved these changes
🎅👍

2021-12-02 18:04 UTC, merged