Artjom Glusonok Lesson 5 Level 5 Task 31 - 33
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #279
Opened 2021-12-03 21:57 UTC by Glusonok

2021-12-03 22:00 UTC, Glusonok commented
Привет . Знаю что проверка правильная , не видет в упор величину массива  . Подскажи пожалуйста . Для меня эта тема с возвратом тёмный лес . Может помнишь на каком уроке проходили мы это :) ?

2021-12-05 14:29 UTC, daniilsjb reviewed
Про `return` и методы было на 3 уроке. Но тут путаница скорее связана с классами и объектами 😅

2021-12-05 14:29 UTC, daniilsjb commented on src/main/java/students/artjom_glusonok/level_5/Arrays.java
> +    int length;
Свойство в этом классе не нужно. Информация о длинне созданного массива уже привязана к самому массиву, поэтому это можно убрать.

2021-12-05 14:29 UTC, daniilsjb commented on src/main/java/students/artjom_glusonok/level_5/Arrays.java
> +    }
Ключевой момент: нужно создать массив именно указанной длины, а не произвольной. То есть:

```java
public int[] create(int length) {
    return new int[length];
}
```

Всё настолько просто! Про свойство я уже сказал выше, эта строчка в принципе не нужна.

2021-12-05 14:29 UTC, daniilsjb commented on src/main/java/students/artjom_glusonok/level_5/Arrays.java
> +        int actualResult = arrays.length;
Собственно, здесь нужно создать массив через класс `Arrays`, и далее сравнить его длинну с ожидаемой:

```java
// Сперва создаём массив указанной длины через Arrays
Arrays arrays = new Arrays();
int[] array = arrays.create(length);

// Далее сравниваем его длину с той, которая была задана
int expectedResult = length;
int actualResult = array.length;
```

Лучше всего этот тест вызвать пару раз, задав разные размерности массива:

```java
test.shouldCreateArray(0);
test.shouldCreateArray(1);
test.shouldCreateArray(10);
```

2021-12-06 20:03 UTC, daniilsjb requested changes

2021-12-06 20:03 UTC, daniilsjb commented on src/main/java/students/artjom_glusonok/level_5/Arrays.java
> +            test.shouldCreateArray(10);
Два теста проваливаются, и о причине я уже указывал в комментариях ранее. Метод `create` надо подправить :)

2021-12-07 20:30 UTC, merged