Homework l5-l4-t31\32\33
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #283
Opened 2021-12-04 10:34 UTC by Denteron

lesson 5 - level 4 -task 31,32,33
3 in ONE

2021-12-05 03:43 UTC, Denteron commented
Посмотрел код и это херня конечно у меня, пойду переделывать :)

2021-12-05 05:26 UTC, Denteron commented
залил куда более адекватный код, сорян что поторопился изначально :)

2021-12-05 15:11 UTC, daniilsjb requested changes
`fillRandomly` реализован не совсем по заданию, да и от лишнего свойства стоит избавиться, чтобы не путало. А вообще выглядит лучше, чем первая версия, так что прогресс :D

2021-12-05 15:11 UTC, daniilsjb commented on src/main/java/students/deniss_fomins/lesson_5/level_5/task_31/Arrays.java
> +    int[] filler;
Тут не должно быть свойства, каждый метод либо принимает, либо возвращает какой-то массив. По сути говоря это stateless класс :)

2021-12-05 15:11 UTC, daniilsjb commented on src/main/java/students/deniss_fomins/lesson_5/level_5/task_31/Arrays.java
> +        return massif;
Сокращается до `return new int[length];`

2021-12-05 15:11 UTC, daniilsjb commented on src/main/java/students/deniss_fomins/lesson_5/level_5/task_31/Arrays.java
> +        }
Ключевой момент: этот метод принимает _массив_ чисел, а не число. И именно переданный массив и нужно заполнить числами.

2021-12-05 15:11 UTC, daniilsjb commented on src/main/java/students/deniss_fomins/lesson_5/level_5/task_31/ArraysTest.java
> +        int[] expectedResult = new int[5];
Переменной `expectedResult` не обязательно быть массивом, это может быть просто число `5`. В конечном итоге мы просто сравниваем два числа.

2021-12-05 15:11 UTC, daniilsjb commented on src/main/java/students/deniss_fomins/lesson_5/level_5/task_31/ArraysTest.java
> +
Ну, демо наверное придётся тоже подправить 🤔 И отформатировать, я местами вижу недостаток пробелов!

2021-12-06 19:54 UTC, daniilsjb approved these changes
🎅👍

2021-12-06 19:54 UTC, merged