Homework l5-l6-t34-38
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #285
Opened 2021-12-05 07:11 UTC by Denteron

lesson 5 - level 6 -task 34/35/36/37/38
5 in ONE

На базе предыдущего задания, изменил только имя объекта, так как он конфликтовал с импортированной библиотекой Array :) Не знаю как это обычно фиксят, но я просто изменил имя класса :)

2021-12-05 15:17 UTC, daniilsjb requested changes
Если действительно возникают конфликты по именам, то придётся использовать названием класса целиком (вместе с пакетом, к которому он принадлежит). Это одна из причин, почему пакеты вообще существуют. Но в этом задании просто не стоит использовать `java.util.Arrays`, а писать всё руками :D

Собственно, новых ошибок здесь нет, просто comeback-и из прошлых заданий. Зато тесты написаны хорошо, моё почтение 👌

2021-12-05 15:17 UTC, daniilsjb commented on src/main/java/students/deniss_fomins/lesson_5/level_6/task_34/Arrays1.java
> +    int min;
Как и раньше, свойства надо убрать. Всё решается через параметры и `return`.

2021-12-05 15:17 UTC, daniilsjb commented on src/main/java/students/deniss_fomins/lesson_5/level_6/task_34/Arrays1.java
> +    }
Возвращаясь к тому предыдущему заданию, здесь я бы тоже хотел видеть просто циклы 😅

2021-12-06 08:14 UTC, Denteron commented
Всё исправлено и доведено до "совершенства" иногда забываю юзать "реформат", но в целом проде теперь уже точно все збз :)

2021-12-06 19:58 UTC, daniilsjb approved these changes
Вот теперь действительно топово, а на класс `Arrays1` просто приятно смотреть 🎅👍

2021-12-06 19:58 UTC, merged