Lesson 5, level 1
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #289
Opened 2021-12-05 17:31 UTC by IDanste

2021-12-06 17:45 UTC, IDanste commented
Доброго вечера. Пытался закинуть второй уровень заданий в этот же pull request, вроде получилось, но и во второй раз сделал коммит первого уровня, как можно удалить полностью, а не по одному файлу?

2021-12-07 20:38 UTC, daniilsjb requested changes
Не уверен, что понимаю вопрос 🤔 Коммитить можно много изменений сразу, то есть создание и удаление нескольких файлов можно сделать одним коммитом. В Pull Request всё вроде сохранилось, так что проблем не вижу.

Но вот начиная с 5-го занятия код нужно форматировать. Рекомендую пройти по каждому файлу с решением и при [помощи IDE](https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html) решить эту проблему :)

2021-12-07 20:38 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/lesson_5/level_2/task_14/Task_14.java
> +}
Этот код нужно отформатировать, вначале каждой строке должно быть 4 пробела. И ещё, при подсчёте среднего арифметического стоит использовать `3.0`, чтобы результат не округлялся.

2021-12-07 20:38 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/level_5/level_1/task_6/Task_6.java
> +}
Здесь тоже нужно отформатировать.

2021-12-07 20:38 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/level_5/level_1/task_7/Task_7.java
> +}
Здесь тоже нужно отформатировать.

2021-12-07 20:38 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/level_5/level_1/task_8/Task_8.java
> +}
Здесь тоже нужно отформатировать.

2021-12-08 16:02 UTC, IDanste commented
Отформатировал и исправил.
Я имел ввиду, про это
![Screenshot_12](https://user-images.githubusercontent.com/93610220/145241035-808fe143-06a3-41d6-91ad-f855ca518cf1.png)
  Когда сделал 2 коммита, которые нужные и третий ненужный, можно его как-то удалить? На лекции Костя сказал, что таким образом можно повредить историю и лучше таким не заниматься.

2021-12-08 20:05 UTC, daniilsjb approved these changes
По-моему как раз наоборот, именно удалением коммитов можно напортачить с историей, поэтому так делать нельзя. Я уточнил у Кости, он говорит то же самое 😅

Я посмотрел на содержимое этого лишнего коммита. Там просто какие-то изменения с добавлением пробелов в комментариях. Возможно вы просто случайно поменяли что-то в этих файлах и сделали коммит с таким же названием? В таком случае всё правильно и ничего удалять не надо 🙂

2021-12-08 20:05 UTC, merged