Lesson 5 - Level 1 - Task 1 up to 9 ArrayDefinition ArrayLength
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #292
Opened 2021-12-06 12:38 UTC by Vklagiss

Cперва делал CalculatorDemo и CalculatorTest в бранче    st-vladislavs-klagiss-lesson-4-level-4    но не закончил и начал делать ArrayDefinition в бранче   st-vladislavs-klagiss-lesson-5-level-1   когда делал  commit  не заметил что все  committed  но хотел  push только  ArrayDefinition  поэтому поставил галочку Push only brach...   и в итоге всё наоборот

Branch  st-vladilavs-klagiss-lesson-5-level-1  перенаправился из  main  в  origin

2021-12-06 12:40 UTC, Vklagiss commented
Calculator i CalculatorTest hotel zakon4itj

2021-12-06 21:04 UTC, daniilsjb requested changes
Если есть желание закончить калькулятор, то надо его слегка подправить. Уж хотя бы добавить фигурных скобок, чтобы компилятор не жаловался :D

2021-12-06 21:04 UTC, daniilsjb commented on src/main/java/students/vladislavs_klagiss/lesson_4/level_4/CalculatorDemo.java
> +        }
Тут будет работать не совсем правильно (один тест сейчас проваливается). Чтобы верно отрабатывались сценарии, где некоторые числа равны, нужно заменить все `>` на `>=` :)

2021-12-06 21:04 UTC, daniilsjb commented on src/main/java/students/vladislavs_klagiss/lesson_4/level_4/CalculatorTest.java
> +        calculatorTest.maxOfThreeNumbersTest4();
Есть ещё три теста `maxOfThreeNumbers`, которые здесь не вызываются.

2021-12-06 21:04 UTC, daniilsjb commented on src/main/java/students/vladislavs_klagiss/lesson_4/level_4/CalculatorTest.java
> +        }
В конце этого класса не хватает двух фигурных скобок, код не будет компилироваться 🤔

2022-01-19 19:05 UTC, daniilsjb approved these changes

2022-01-19 19:06 UTC, merged