Homework for lesson 5
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #295
Opened 2021-12-06 15:33 UTC by Romkiin

2021-12-07 20:53 UTC, daniilsjb requested changes
Очень хорошо! Есть пара мометов, в основном касаются форматирования или небольшого несоответствия с заданиями :)

2021-12-07 20:53 UTC, daniilsjb commented on src/main/java/students/romans_sodnaks/lesson_5/level_2/task_15/Array6.java
> +        }
В этом задании нужно увеличить значение каждой ячейки на два. Иными словами, нужно изменить сам массив, и далее вывести его на консоль. Здесь программа почему-то пытается прибавить 0 к каждому элементу массива и выводит на экран сам 0, игнорируя результат 🤔

Код решения будет выглядеть примерно так:

```java
for (int i = 0; i < numbers.length; i++) {
    // Здесь нужно прибавить 2 к ячейке numbers[i]
    // Подскажу: придётся использовать оператор +=
}

// Теперь массив был изменён, можно просто вывести его в консоль
for (int i = 0; i < numbers.length; i++) {
    System.out.println("values[" + i + "] = " + numbers[i]);
}
```

2021-12-07 20:53 UTC, daniilsjb commented on src/main/java/students/romans_sodnaks/lesson_5/level_3/task_24/ForLoopDefinition9.java
> +        }
Цикл должен выводить числа от 0 до 100. Следовательно, нужно 100 итераций, а не 10.

2021-12-07 20:53 UTC, daniilsjb commented on src/main/java/students/romans_sodnaks/lesson_5/level_4/task_25/Solution.java
> +        System.out.println("Please enter Massive length: ");
На всякий случай: массив называется "array".

2021-12-07 20:53 UTC, daniilsjb commented on src/main/java/students/romans_sodnaks/lesson_5/level_4/task_27/Solution.java
> +            }
Блоки кода всегда стоит окружать фигурными скобками, тогда код легче читать и расширять. То есть, должно быть так:

```java
for (int i = 1; i < numbers.length; i++) { // фигурная скобка
    if (numbers[i] > max) {
        max = numbers[i];
    }
} // фигурная скобка
```

2021-12-07 20:53 UTC, daniilsjb commented on src/main/java/students/romans_sodnaks/lesson_5/level_4/task_28/Solution.java
> +            }
Здесь тоже нужно добавить фигурные скобки.

2021-12-07 20:53 UTC, daniilsjb commented on src/main/java/students/romans_sodnaks/lesson_5/level_4/task_29_30/Solution.java
> +        }
Здесь нужно добавить фигурные скобки после `else`.

2021-12-07 20:53 UTC, daniilsjb commented on src/main/java/students/romans_sodnaks/lesson_5/level_5/task_31_33/Arrays.java
> +    int[] array;
Свойство `array` не нужно, каждый метод этого класса либо возвращает новый массив, либо принимает уже существующий.

2021-12-07 20:53 UTC, daniilsjb commented on src/main/java/students/romans_sodnaks/lesson_5/level_5/task_31_33/Arrays.java
> +        return numbers;
Можно сократить до `return new int[length];`

2021-12-07 20:53 UTC, daniilsjb commented on src/main/java/students/romans_sodnaks/lesson_5/level_5/task_31_33/Arrays.java
> +        }
Вместо `this.array[i]` нужно использовать просто `array[i]`. Первую строчку достаточно просто убрать, поскольку свойства быть не должно.

2021-12-08 07:27 UTC, Romkiin commented on src/main/java/students/romans_sodnaks/lesson_5/level_5/task_31_33/Arrays.java
> +    int[] array;
Когда я убираю строку int[] array;  он показивает ошибку.

2021-12-08 19:50 UTC, daniilsjb approved these changes
🎅👍

2021-12-08 19:50 UTC, daniilsjb commented on src/main/java/students/romans_sodnaks/lesson_5/level_2/task_15/Array6.java
> +            numbers[i] += 2 + random.nextInt(10);
Прибавлять случайное число было не нужно 😄

2021-12-08 19:50 UTC, daniilsjb commented on src/main/java/students/romans_sodnaks/lesson_5/level_5/task_31_33/Arrays.java
> +    int[] array;
Да, это потому что в методе `fillRandomly` нужно было убрать первую строчку (где `this.array = array`) и везде убрать `this.`

2021-12-08 19:50 UTC, merged