Artjom Glusonok Lesson 5 Level 5 Task 34
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #312
Opened 2021-12-08 20:40 UTC by Glusonok

2021-12-08 20:45 UTC, Glusonok commented
Привет . Вопрос , почему у меня постоянно при проверки одни массивы а другие обычные . Не могу в эту ерунду въехать вообще . :) хоть и понимаю что такое массивы и что обычные числа . И ещё я тут психовал  и клацал ерунду всякую , теперь там где номер строки в ители у мня появилась @ , как убрать XD ? Спасибки .

2021-12-09 13:38 UTC, daniilsjb requested changes
Ммм, что конкретно не ясно с массивами? Они просто позволяют создавать наборы каких-то данных. Например, если бы мы спросили тысячу человек их возраст и захотели сохранить эту информацию в программе, то создавать по одной переменной на каждого человека было бы... затруднительно:

```java
int age1 = 23;
int age2 = 64;
int age3 = 15;
...
int age1000 = 46;
```
Мало того, что это очень много работы, так у нас ещё и нет возможности легко изменить количество возрастов. Что если мы для верности решили опросить на сотню людей больше? Придётся добавлять ещё 100 переменных.

Что ещё хуже, у нас нет удобного способа объединить все эти переменные вместе. Что, если мы хотим найти средний возраст всех людей? Нам бы пришлось писать вот такое выражение:

```java
double avg = (age1 + age2 + age3 + ... + age1000) / 1000.0;
//                                  ^
//                    тут ещё 996 таких же сложений
```

Ужас какой, я не хочу перечислять каждый возраст по отдельности. Именно для этого и были придуманы массивы:

```java
// Вместо тысячи переменных мы создали одну переменную с тысячью элементами.
int[] ages = new int[1000];

// Теперь нам не нужно перечислять каждый возраст по отдельности. Мы знаем
// количество возрастов, и мы знаем, что у каждого возраста есть свой индекс.
// Достаточно применить простой цикл.
int sum = 0;
for (int i = 0; i < ages.length; i++) {
    sum += ages[i];
}

// Опять-таки, количество элементов в массиве нам известно. Даже если бы мы
// опросили миллион людей, этот код остался бы без изменений.
double avg = sum / (double)ages.length;
```

2021-12-09 13:38 UTC, daniilsjb commented on src/main/java/students/artjom_glusonok/lesson_5/level_6/Arrays.java
> +            array[i] = 10;
Этот метод должен выводить значение каждой ячейки, а не изменять. Нужен обыкновенный `System.out.println`.

2021-12-09 13:38 UTC, daniilsjb commented on src/main/java/students/artjom_glusonok/lesson_5/level_6/Arrays.java
> +    }
Для этого задания тест не нужен, но вот демо можно и написать. Достаточно создать пару массивов и показать, что если вызвать `print`, то они будет выведены на консоли. Что-то типа такого:

```java
class ArraysDemo {
    public static void main(String[] args) {
        Arrays arrays = new Arrays();

        int[] a = {1, 2, 3};
        int[] b = {9};

        arrays.print(a);
        System.out.println();

        arrays.print(b);
        System.out.println();
    }
}
```

2021-12-09 18:40 UTC, Glusonok commented
Что такое массивы и числа я понимаю . У меня ситуация постоянно как на фото я создал массив и при проверке мне сообщает что что параметры разные , в одном месте массив в другом число . Где и что я не правильно делаю . Не понимаю :( ![20211209_203651.jpg](https://user-images.githubusercontent.com/93610188/145456085-9e0d13b7-2432-45c0-81d1-abc019585331.jpg) . И там же на фото есть знак @ про который говорил , там где строки кода . Как его убрать ?

2021-12-10 21:41 UTC, daniilsjb commented
В объявлении метода указано, что `array` - это `int[]`. Квадратные скобки всегда означают, что речь идёт о массивах. Когда программа передаёт в метод что-то через круглые скобки, эти значения должны совпадать с тем, что ожидает метод, иначе компилятор будет жаловаться. Например, если метод ожидает строку, а мы передаём число, то где-то что-то пошло не так: либо сам метод составлен неправильно, либо он неправильно вызывается.

Здесь метод совершает операции на массивах (он должен вывести содержимое массива в консоль). Значит, проблема в том месте, где мы этот метод вызываем, то есть в `main`. Действительно, когда компилятор видит `10`, он считает это _числом_, а нужен _массив_. Значит, нужно создать массив и передать его:

```java
public static void main(String[] args) {
    int[] myArray = {1, 2, 3, 4};
    arrayTest.printTest(myArray);
}
```

Или даже так:

```java
public static void main(String[] args) {
    arrayTest.printTest(new int[] {1, 2, 3, 4});
}
```

Касаемо `@`, я на эту штуку никогда не обращал внимания, так что по правда говоря не могу сказать, что это 🤔 Но я нашёл вот [эту страницу в документации](https://www.jetbrains.com/help/idea/external-annotations.html), там указано, как это можно скрыть 😅

2021-12-11 02:06 UTC, Glusonok commented
Приве . Ок . Я создал 4 массива при тести , как мне теперь к тесту привязать количество массивов , макс массив и мин массив ?  И кстати по поводу @ , я так понял это делать типо горячие клавиши на часто используемые коды . Вот , а убрать можно ( приложил фотки ) . Спасибо за терпение 🤣![20211211_040101.jpg](https://user-images.githubusercontent.com/93610188/145660261-4a91daa2-b42c-49c2-a410-a5cbe597f061.jpg)![20211211_040045.jpg](https://user-images.githubusercontent.com/93610188/145660265-ecbaefae-3cfe-4bb9-ae4e-1c95e6840012.jpg)

2021-12-11 11:55 UTC, daniilsjb reviewed
Рад, что иконку получилось убрать 🥳

2021-12-11 11:55 UTC, daniilsjb commented on src/main/java/students/artjom_glusonok/lesson_5/level_6/Arrays.java
> +            array[i] = 10;
Здесь всё ещё нужно исправить.

2021-12-11 11:55 UTC, daniilsjb commented on src/main/java/students/artjom_glusonok/lesson_5/level_6/Arrays.java
> +        }
Этот тест можно убрать, как я говорил ранее для вывода в консоль тесты писать не нужно. Лучше написать демонстрацию, создать там массив и вызвать на нём этот метод :)

2021-12-11 11:55 UTC, daniilsjb commented on src/main/java/students/artjom_glusonok/lesson_5/level_6/Arrays.java
> +        }
Как и обычно, в каждом тесте нужно сперва составить тестовые данные. Например, для поиска наименьшего числа:

```java
int[] array = {5, 8, 1, 10};
int expectedResult = 1;
```

Далее вызываем метод и смотрим, правильный ли результат:

```java
Arrays subject = new Arrays();

int[] array = {5, 8, 1, 10};
int expectedResult = 1;
int actualResult = subject.findMin(array);

assertThatEqual(expectedResult, actualResult,  "Find min");
```

И так в каждом тесте.

2021-12-11 11:55 UTC, daniilsjb commented on src/main/java/students/artjom_glusonok/lesson_5/level_6/Arrays.java
> +        public static void main(String[] args) {
Кстати говоря, каждый класс нужно делать в отдельном файле. Рекомендую создать в этом же пакете файл `ArraysTest.java` и переместить туда всё содержимое этого класса, но без `static` :)

2021-12-13 14:23 UTC, daniilsjb approved these changes
🎅👌

2021-12-13 14:23 UTC, daniilsjb commented on src/main/java/students/artjom_glusonok/lesson_5/level_6/Arrays.java
> +            array[i] = array.length;
Имелось ввиду `System.out.println(array[i]);` 🙂

2021-12-13 14:23 UTC, merged