Homework for lesson 5, levels 1-3
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #340
Opened 2021-12-13 15:25 UTC by svetlanacibula

Please check my homework from lesson 5

2021-12-13 15:56 UTC, daniilsjb requested changes
В задании 15 маленький недочёт, в остальном прекрасно :)

2021-12-13 15:56 UTC, daniilsjb commented on src/main/java/students/svetlana_cibula/lesson_5/level_2/task_15/ArrayOfThreeRandomPlusTwo.java
> +        }
Важный момент: по заданию требуется именно увеличить значения самих ячеек, то есть так, чтобы был изменён сам массив. Для этого понадобится отдельный цикл:

```java
for (int i = 0; i < numbers.length; i++) {
    numbers[i] += 2;
}

// выводим содержимое в консоль, как есть...
```

2021-12-13 15:56 UTC, daniilsjb commented on src/main/java/students/svetlana_cibula/lesson_5/level_2/task_14/ArrayAverageOfThreeRandom.java
> +        double avg = sum / (numbers.length * 1.0);
Для таких целей существует специальный синтаксис преобразования типов: `sum / (double)numbers.length`, лучше его использовать по возможности.

2021-12-14 11:10 UTC, svetlanacibula commented on src/main/java/students/svetlana_cibula/lesson_5/level_2/task_15/ArrayOfThreeRandomPlusTwo.java
> +        }
Спасибо! Всё поправила и запушила.

2021-12-14 20:43 UTC, daniilsjb approved these changes
Отлично! 🥳

2021-12-14 20:43 UTC, merged