Dan Stepanov lesson 2 tasks 1-8 solutions
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #41
Opened 2021-11-14 08:47 UTC by IDanste

2021-11-14 13:55 UTC, daniilsjb requested changes
Есть небольшая ошибка в первых двух заданиях. 😅

Ещё прошу обязательно придерживаться принятой структуры проекта при решении заданий. Нужно добавлять свои работы по пути `students/<student-name>/<lesson>/<level>`, можно даже делать для каждого отдельного таска свою папочку.

Например:
* `students/dan_stepanov/lesson_2/level_1/task_1/Solution.java`
* `students/dan_stepanov/lesson_2/level_2/task_3/Phone.java`

Чтобы создать папочку, нужно нажать правой кнопкой мышки по папке-родителю (например, `students`), далее `New → Package`. Таким образом можно просто создать все эти папки, передвинуть туда файлы с решениями, и git позволит сохранить эти изменения при следующем коммите.

Переименовать файлы также можно через правую кнопку мыши, далее `Refactor → Rename...` или `Refactor → Rename File...`. Надеюсь, что не запутал 😄

2021-11-14 13:55 UTC, daniilsjb commented on src/main/java/HomeWorkDStask1.java
> +        System.out.println("Show division results: " +multiply);
Здесь программа дважды выводит результат умножения. Не порядок! :)

2021-11-14 13:55 UTC, daniilsjb commented on src/main/java/HomeWorkDStask2.java
> +        System.out.println("Show double division results: " +multiply);
Здесь тоже второе умножение тоже должно быть делением 🤔

2021-11-15 04:31 UTC, IDanste commented
Спасибо за найденные ошибки. Получилось так, что сначала делал задания
полностью в новом проекте, а после через копипаст уже переделал в отдельную
ветку, не заметил. :(

Вс, 14 нояб. 2021 г. в 15:55, Daniils Buts ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Есть небольшая ошибка в первых двух заданиях. 😅
>
> Ещё прошу обязательно придерживаться принятой структуры проекта при
> решении заданий. Нужно добавлять свои работы по пути
> students/<student-name>/<lesson>/<level>, можно даже делать для каждого
> отдельного таска свою папочку.
>
> Например:
>
>    - students/dan_stepanov/lesson_2/level_1/task_1/Solution.java
>    - students/dan_stepanov/lesson_2/level_2/task_3/Phone.java
>
> Чтобы создать папочку, нужно нажать правой кнопкой мышки по папке-родителю
> (например, students), далее New → Package. Таким образом можно просто
> создать все эти папки, передвинуть туда файлы с решениями, и git позволит
> сохранить эти изменения при следующем коммите.
>
> Переименовать файлы также можно через правую кнопку мыши, далее Refactor
> → Rename... или Refactor → Rename File.... Надеюсь, что не запутал 😄
> ------------------------------
>
> In src/main/java/HomeWorkDStask1.java
> <https://github.com/konstantins-buts/jg-java-1-online-autumn-tuesday-2021/pull/41#discussion_r748855952>
> :
>
> > +        System.out.println("Show multiply results: " +multiply);
> +        System.out.println("Show division results: " +multiply);
>
> Здесь программа дважды выводит результат умножения. Не порядок! :)
> ------------------------------
>
> In src/main/java/HomeWorkDStask2.java
> <https://github.com/konstantins-buts/jg-java-1-online-autumn-tuesday-2021/pull/41#discussion_r748855983>
> :
>
> > +        System.out.println("Show double multiply results: " +multiply);
> +        System.out.println("Show double division results: " +multiply);
>
> Здесь тоже второе умножение тоже должно быть делением 🤔
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/konstantins-buts/jg-java-1-online-autumn-tuesday-2021/pull/41#pullrequestreview-805473264>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWKGB3BILQNF7HN236XKQV3UL65W3ANCNFSM5H7TPQYQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-15 14:41 UTC, daniilsjb commented
Если что, я могу сам подправить структуру файлов, в будущем её просто стоит придерживаться. Но это было бы хорошим упражнением в работе с git и IntelliJ 😄

2021-11-15 16:13 UTC, IDanste commented
Переделал, но немного химии наделал. (^_^)

2021-11-15 19:54 UTC, daniilsjb approved these changes
Отлично! 🧐👍

2021-11-15 19:54 UTC, merged