Homework
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #43
Opened 2021-11-14 14:33 UTC by Romkiin

2021-11-15 14:48 UTC, daniilsjb requested changes
В решении заданий всё хорошо, но почему они все находятся в пакете инструктора? 😅

Мы придерживаемся структуры `students/<student-name>/<lesson>/<level>/<task>`. Очень прошу создать личный пакет для заданий и перенести туда все файлы с решениями. При следующем коммите git позволит сохранить все переносы файлов.

Также не стоит оставлять комментарии в коде инструктора, лучше делать пометки где-то за пределами публичной репозитории, или хотя бы в собственном коде. :)

Если возникают проблемы, я могу помочь перетащить всё на свои места и убрать лишние изменения, но в будущем нужно придерживаться правильной структуры! 😉

2021-11-15 14:50 UTC, Romkiin commented
Да у меня с папками там каша вышла 😆

2021-11-16 19:46 UTC, daniilsjb approved these changes
Отлично! Я также убрал некоторые лишние изменения, так что теперь всё топ 🧐👍

2021-11-16 19:46 UTC, daniilsjb commented on src/main/java/students/romans_sodnaks/lesson_2/level_1/task_1/Solution.java
> +        int r3 = p1 % p2;
Технически это оператор modulo, а не умножение 🤔

2021-11-16 19:46 UTC, merged