St pavels fomins lesson 9 level 1 task 6
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #455
Opened 2022-01-07 18:35 UTC by nextlevelplay

2022-01-08 21:26 UTC, daniilsjb requested changes
Стоит добавить ещё как минимум геттеры, хотя есть и другие полезные методы.

2022-01-08 21:26 UTC, daniilsjb commented on src/main/java/students/pavels_fomins/lesson_9/level_1/task_6/Book.java
> +}
Описание задания однозначно составлено странно, но в текущем виде этот класс почти бесполезный, поскольку с ним вообще ничего нельзя сделать. Инкапсуляция не подразумевает только использование `private`, чтобы скрыть какие-то данные. Она подразумевает, что операции на объекте проходят через его методы, а не напрямую через его поля/свойства.

Книга - это модель данных. Она должна предоставлять доступ к какой-то информации, при этом не позволяя нам изменять то, что менять не имеет смысла. Например, ни название, ни автор книги после выпуска не меняются, поэтому сеттеры не нужны (эти поля можно даже сделать `final`). Но есть вещи, которые стоило добавить:

-  геттеры
-  equals (опционально)
-  hashCode (опционально)
-  toString (опционально)

Понимаю, что это неочевидно, но вокруг инкапсуляции строится много ложных мифов, так что стоит учиться мыслить правильно. Спойлер, но в [`lesson_9/demo_5/Book.java`](https://github.com/konstantins-buts/jg-java-1-online-autumn-tuesday-2021/blob/main/src/main/java/instructor/lesson_9/demo_5/Book.java) есть пример подходящего кода :)

2022-01-08 23:58 UTC, nextlevelplay commented on src/main/java/students/pavels_fomins/lesson_9/level_1/task_6/Book.java
> +}
Понял, спасибо. В последних заданиях очень "подсел" на перезапись toString - очень крутая штука, когда дело доходит до распечатки)) А меня хлебом не корми, дай напечатать чего-нибудь :)

2022-01-09 10:03 UTC, daniilsjb approved these changes
Рад, что `toString` понравился, это очень полезный метод :D

2022-01-09 10:04 UTC, merged