St dan stepanov lesson 6 level 4 task 21
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #521
Opened 2022-01-18 16:43 UTC by IDanste

Отмучился около часа, вроде как разобрался и не происходит конфликта.

2022-01-19 18:44 UTC, daniilsjb requested changes
Рад, что конфликтов не возникло. Но есть маленькая проблемка с индексами в циклах, стоит подправить 😄

2022-01-19 18:44 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/lesson_6/level_4/task_21/ArrayStock.java
> +                for (int b = 0; b < array.length; b++) {
Во всех циклах стоит проявить осторожность: поскольку размерности у массива могут быть разные, то внутренняя проверка должна быть `b < array[a].length`, то есть сравниваться с размерностью внутреннего массива. Если сейчас сделать массив 3x2, то программа вылетит с ошибкой 😥

2022-01-19 18:44 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/lesson_6/level_4/task_21/ArrayStock.java
> +                for (int b = 0; b < array.length; b++) {
Ещё здесь.

2022-01-19 18:44 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/lesson_6/level_4/task_21/TwoDimensionalArray.java
> +                for (int b = 0; b < array.length; b++) {
И здесь.

2022-01-19 18:44 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/lesson_6/level_4/task_21/ArrayStock.java
> +        }
Альтернативно можно всегда делать массив квадратным, т.е. давать одинаковые ширину и высоту. Но понятное дело, что это уже будет решением другой задачи 🤔

2022-01-20 08:19 UTC, IDanste commented
Вроде как подправил, случайно нашел, что прямо здесь на гитхабе можно ошибки исправлять? Когда делал следующие задания, удалил ветку с этим решением и уже переписал код заново, в последний момент увидел, можно ошибки устранять прямо здесь.

2022-01-20 16:05 UTC, daniilsjb approved these changes
В принципе можно и здесь поправлять, но с этим лучше поосторожнее. Если написать некомпилирующийся код, то github этого не подметит 🤔

2022-01-20 16:05 UTC, merged