Lesson 10 - Level 5 - Task 13-18 (ALL IN ONE) Solution
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #540
Opened 2022-01-21 17:24 UTC by nextlevelplay

2022-01-22 19:24 UTC, daniilsjb approved these changes
Метод `searchByAuthor` делает не совсем то, что нужно, так что стоит подправить. В остальном это упрощения и всякие рекомендации :)

2022-01-22 19:24 UTC, daniilsjb commented on src/main/java/students/pavels_fomins/lesson_10/level_5/task_13/BookReader.java
> +    boolean print();
Этому методу не нужно ничего возвращать, поскольку он просто выводит книги в консоль. Сюда лучше подходит `void`.

2022-01-22 19:24 UTC, daniilsjb commented on src/main/java/students/pavels_fomins/lesson_10/level_5/task_13/BookReader.java
> +    boolean searchByAuthor(String author);
Этот метод должен _возвращать_ книги по автору, то есть `boolean` тут недостаточно, нужен скорее `List<Book>`.

2022-01-22 19:24 UTC, daniilsjb commented on src/main/java/students/pavels_fomins/lesson_10/level_5/task_13/BookReaderImpl.java
> +    private final ArrayList<Book> memory;
Лучше при объявлении списка всегда использовать _интерфейс_ `List` вместо конкретных реализаций. В таком случае мы можем беспрепятственно менять реализации в зависимости от требований программы, и при этом ничего в коде не сломается:

```java
class BookReaderImpl implements BookReader {

  private final List<Book> memory;

    public BookReaderImpl() {
        // Если нужен LinkedList, то достаточно изменить только эту строку.
        this.memory = new ArrayList<>();
    }
}
```

2022-01-22 19:24 UTC, daniilsjb commented on src/main/java/students/pavels_fomins/lesson_10/level_5/task_13/BookReaderImpl.java
> +    }
Мне кажется этот метод должен быть приватным 🤔

Также есть пара упрощений. Во-первых, у списка уже есть метод `contains`, так что вручную смотреть, содержит ли список нужную нам книгу не надо. Во-вторых, поскольку книга не меняется, то проверять, является ли она пустой при каждой итерации всё равно не имеет смысла.

Так что я бы предложил переписать как-то так:

```java
private boolean checker(Book book) {
    return memory.contains(book) || book.getAuthor().equals("") || book.getTitle().equals("");
}
```

Но вообще, возможно писать для этого отдельный метод не стоит, поскольку эта проверка актуальна только для метода `add`.

2022-01-22 19:24 UTC, daniilsjb commented on src/main/java/students/pavels_fomins/lesson_10/level_5/task_13/BookReaderImpl.java
> +    }
Тут всё значительно проще: метод `remove` уже возвращает то, что нам надо :)

```java
@Override
public boolean delete(Book book) {
    return memory.remove(book);
}
```

2022-01-22 19:24 UTC, daniilsjb commented on src/main/java/students/pavels_fomins/lesson_10/level_5/task_13/BookReaderImpl.java
> +            if (value.getAuthor().equals(author) || value.getAuthor().charAt(0) == author.charAt(0)) {
Лучше эту проверку просто заменить на `value.getAuthor().startsWith(author)`. В задании нигде не сказано, что совпадать должны только первые символы 😄

2022-01-22 19:24 UTC, daniilsjb commented on src/main/java/students/pavels_fomins/lesson_10/level_5/task_13/BookReaderImpl.java
> +    }
И да, этот метод должен вернуть все книги, которые были написаны этим автором, поэтому завершать цикл на первой найденной книге нельзя. Если такого автора в репозитории нет, то возвращаем пустой список.

2022-01-22 19:24 UTC, daniilsjb commented on src/main/java/students/pavels_fomins/lesson_10/level_5/task_13/BookReaderTest.java
> +    }
Соотственно, в тестах проверка будет посложнее, придётся подготовить ожидаемый список книг 🤔

2022-01-22 19:24 UTC, daniilsjb requested changes
Упс, не туда нажал 😅

2022-01-22 19:45 UTC, nextlevelplay commented on src/main/java/students/pavels_fomins/lesson_10/level_5/task_13/BookReaderImpl.java
> +    }
checker я использовал ещё в другом Левеле 6 - где надо добавлять как "Прочитанные" и "Не прочитанные", хотя и там я могу тоже использовать contains...чувствую и там переписывать придётся 👀 🤦‍♂️

2022-01-22 19:52 UTC, nextlevelplay commented on src/main/java/students/pavels_fomins/lesson_10/level_5/task_13/BookReader.java
> +    boolean print();
написал на boolean, так как проверка нужна была на этот метод. Думал, что распечатав книги вернуть "тру" - значит всё гуд 😂 Как написать проверку на воид - пойду пороюсь в гугле 😁

2022-01-22 19:55 UTC, daniilsjb commented on src/main/java/students/pavels_fomins/lesson_10/level_5/task_13/BookReader.java
> +    boolean print();
Так не нужно, мы не тестируем логику ввода/вывода. Поставлю вопрос так, если метод _всегда_ возвращает `true`, что даст нам тест, который это проверяет? Я могу написать такую реализацию `print`:

```java
@Override
public boolean print() {
    return true;
}
```

И она пройдёт тест. Работает ли она? Нет, поскольку она ничего не выводит в консоль. Тогда в чём вообще смысл теста? 🤔

2022-01-23 17:43 UTC, daniilsjb commented on src/main/java/students/pavels_fomins/lesson_10/level_5/task_13/BookReaderImpl.java
> +    }
Можно сделать так: поскольку левел 6 является продолжением, то этот PR я могу замерджить, а пофиксить недочёты уже придётся там 🤔

2022-01-24 18:33 UTC, daniilsjb approved these changes
💪

2022-01-24 18:33 UTC, merged