Lesson 10 - Level 2 - Task 4   Three variants DayOfTheWeekDetectoran…
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #569
Opened 2022-01-28 12:59 UTC by Vklagiss

…d test

2022-01-28 13:01 UTC, Vklagiss commented
не поставил пробел  DayOfTheWeekDetector and test

2022-01-28 15:04 UTC, daniilsjb requested changes
Нужно подправить названия тестов, методы всегда начинаются с маленькой буквы. Реализация на массиве также не совсем верная, но это опциональная часть задания.

2022-01-28 15:04 UTC, daniilsjb commented on src/main/java/students/vladislavs_klagiss/lesson_10/level_2/task_4/ArrayDayOfTheWeekDetector.java
> +        }
Я бы сказал, что это всё ещё решение на `if`/`else`, а не на массивах. Можно сделать гораздо проще: в самом массиве хранить названия дней недели, и тогда достаточно просто вернуть элемент под индексом `number - 1` (помним, что ячейки начинаются от нуля). Единственное, что нужно сперва проверить, не находится ли `number` за пределами 1-7. Если так, то возвращаем `"Please input a valid number between 1 and 7"`, как и сейчас.

2022-02-22 15:43 UTC, daniilsjb approved these changes

2022-02-22 15:43 UTC, merged