Lesson 8, level 4 Ready, but with question.
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #615
Opened 2022-02-06 09:30 UTC by IDanste

Вопрос о тестах с треугольниками. Почему тесты не хотят проходить проверку, если результат получается не целым? Не могу понять.

2022-02-06 17:53 UTC, daniilsjb requested changes
IDE должна была подсветить жёлтым то место в коде, из-за которого возникает эта ошика. В целом если код работает не так, как нужно, то в первую очередь стоит рассмотреть все Warning-и, которые оставляет компилятор :)

Только есть ещё один момент: для равностороннего треугольника нас не интересует его высота, а только длина стороны. Поэтому формула там будет немного другая, но это можно найти в гугле. 😄

2022-02-06 17:53 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/lesson_8/level_4/task_15/EquilateralTriangle.java
> +    }
Проблема в этой строчке кода. Дело в том, что тут все числа целые, поэтому и результат операции всегда будет целым (округлённым). Преобразование в возвращаемый тип `double` происходит уже после того, как был посчитан округлённый результат. Невероятно, но чтобы исправить, достаточно добавить всего два символа:

```java
@Override
double calculateArea() {
    return ((side * height) / 2.0);
}
```

Теперь `2.0` является константой типа `double`, и результат сможет быть не только целым :)

2022-02-06 17:53 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/lesson_8/level_4/task_15/Triangle.java
> +    }
Здесь та же самая проблема.

2022-02-06 17:53 UTC, daniilsjb commented on src/main/java/students/dan_stepanov/lesson_8/level_4/task_15/EquilateralTriangle.java
> +    }
Кстати, у равностороннего треугольника формула площади другая, в ней не используется высота. Этому классу нужно принимать только длину стороны, и больше ничего. Других видов треугольников не надо, так что второй класс `Triangle` можно даже убрать.

2022-02-07 16:53 UTC, IDanste commented
После болезни и без практики немного забылось, даже немного стыдно стало по-поводу double. Пересмотрел домашку, непонятно зачем два треугольника сделал, одни вопросы к самому себе :D
Единственный вопрос к формулам, про какие ты имел ввиду? Есть высота и сторона, с углами и Герон. Я какую-то пропустил?

2022-02-08 11:29 UTC, daniilsjb commented
Я имел ввиду [вот эту формулу](https://www.cuemath.com/measurement/area-of-equilateral-triangle/): `Math.sqrt(3.0) / 4.0 * a * a;`, мне стоило указать это сразу 😅

2022-02-08 11:51 UTC, IDanste commented
Теперь вроде должно быть Check :)

2022-02-08 11:57 UTC, daniilsjb approved these changes
Высоту из класса теперь можно было убрать, но это уже ладно. Шикардос 🔥

2022-02-08 11:57 UTC, merged