Lesson 14 - Level 1 - Task 1-6 (ALL IN ONE) Solution
konstantins-buts/jg-java-1-online-autumn-tuesday-2021 pull request #653
Opened 2022-02-12 00:25 UTC by nextlevelplay

2022-02-12 00:28 UTC, nextlevelplay commented
Сделал совсем не так как показано в задаче далее, думал мы прошли стримы и нужно решить задачу используя их. 
Если нужно, я переделаю - но результат меня очень порадовал😄. Кода минимум, и фермер доволен 😆

2022-02-12 17:15 UTC, daniilsjb requested changes
Комментарий получился длинее, чем я рассчитывал, но раз уж на этом левеле речь зашла об универсальности, то есть над чем задуматься 😅

2022-02-12 17:15 UTC, daniilsjb commented on src/main/java/students/pavels_fomins/lesson_14/level_1/task_1_6_all_in_one/FruitStorage.java
> +    }
Со стримами-то ладно, но есть момент касаемо того, что нужно возвращать из этих методов: `findAppleByColor()` возвращает список яблок, у которых цвет совпадает с указанным (нас интересуют сами яблоки, а не их общий вес); `findAllHeavyApples()` тоже должен возвращать список яблок.

Сейчас оба метода возвращают `String`. Это не совсем хорошо, поскольку теперь они стали менее универсальными :/ Например, если я хочу найти количество всех красных яблок, то я не могу для этого использовать метод `findAppleByColor()`, потому что он уже считает вес. Тогда мне придётся писать отдельный метод, хотя я мог бы написать код такого рода:

```java
var redApples = storage.findAppleByColor("red");
System.out.println("There are a total of " + redApples.size() + " red apples");
```

Но допустим, мы могли написать разные методы для подсчёта количества яблок и для подсчёта их общего веса (но тогда `findAppleByColor()` стоит переименовать во что-то другое). Теперь предположим другой сценарий: я хочу посчитать общий вес красных и зелёных яблок, и вывести в консоль. Концептуально это сделать тривиально:

```java
var redApplesWeight = findAppleWeightByColor("red");
var greenApplesWeight = findAppleWeightByColor("green");
var totalWeight = redApplesWeight + greenApplesWeight;

System.out.println("The total weight of red and green apples is " + totalWeight);
```

Но опять-таки, я не могу так сделать, поскольку оба метода уже возвращают созданную строку. То есть, у меня нет контроля над тем, в каком формате я вывожу в консоль информацию о весе - это уже решено за меня. Сплошные проблемы 😥

2022-02-13 02:29 UTC, nextlevelplay commented on src/main/java/students/pavels_fomins/lesson_14/level_1/task_1_6_all_in_one/FruitStorage.java
> +    }
Если я правильно понял, нужно оставить на возврат Лист - в принципе не слишком сильно поменяется код. 
А возвращать всегда лучше объекты? Просто я подумал, что вроде очень удобно: Фермер захотел узнать чего-то, использовал метод и получил кол-во согласно цвету, единственное не учёл, что у него яблоки поштучно 😆

Тесты отвалились само собой, но с такой реализацией пришлось в Ожидаемый результат закинуть Лист из Яблок, просто сравнение со строкой не проходил, хотя выход 1 в 1. Как обойти одинаковые на взгляд, но видимо разные внутри не смог понять, поэтому создал Лист. Более громоздко получилось или я просто уже привык к сравнению через [Apple{color='red', weight=100}, Apple{color='red', weight=160}, Apple{color='red', weight=200}] - а возможно это дурной тон😄

2022-02-13 11:47 UTC, daniilsjb commented on src/main/java/students/pavels_fomins/lesson_14/level_1/task_1_6_all_in_one/FruitStorage.java
> +    }
Код действительно изменился не сильно. Я бы даже сказал, что он стал проще 🧐

Касаемо того, что возвращать. Существует разница между _данными_ и _презентацией_ данных. Данные просто описывают что-то. Например, набор яблок. Презентация берёт эти данные и показывает их пользователю в каком-то красивом формате. Скажем, в виде текста в консоли.

Когда мы разделяем данные от презентации, мы делаем код более универсальным. Я могу взять набор всех красных яблок и затем напечатать их в консоль, или обернуть в JSON и отправить куда-то по сети. Смысл в том, что логика, ответственная за поиск красных яблок, в обоих случаях остаётся одинаковой: меняется только то, как мы эти данные используем. Задача этой логики лишь в том, чтобы предоставить данные, а другая часть системы может их как-то презентовать.

Поэтому возвращать сразу строку нежелательно, гораздо лучше вернуть список яблок и создать на основе него строку уже где-то в методе `main`. Такой подход к разработке будет очень полезен при работе с реальными фреймворками типа Spring 😎

2022-02-13 11:47 UTC, daniilsjb approved these changes
🔥

2022-02-13 11:47 UTC, merged